CREATE TABLE 'People' (
	'PersonID'	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	'FullName'	TEXT NOT NULL,
	'DateOfBirth'	TEXT NOT NULL,
	'ScreenName'	TEXT NOT NULL,
	'IsAdult'	INTEGER NOT NULL
);